### ISSUE TITLE
Forward ESC to evil-surround

### ISSUE THREAD

**Issue by hlissner** [cute-jumper/evil-embrace.el#2]
I think it would be more sensible for ESC to abort the surround, rather than surround with `^[`'s. This can be fixed either by adding `?\C-\[` to `evil-embrace-evil-surround-keys` (evil-surround has an abort-on-esc fallback) or have evil-embrace itself handle escapes appropriately.

Great plugin, by the way!

**Comment by cute-jumper** [comment]
Thanks for the suggestion and nice words! For the time being, I think it is fine to just let `evil-surround` handle the <kbd>ESC</kbd> for `evil-embrace`. So I just passed the <kbd>ESC</kbd> to `evil-surround`. Let me know if there is any problem. Thanks!

**Comment by casouri** [comment]
Maybe update this change in README?

**Comment by casouri** [comment]
Maybe it's my problem, but could you try to reproduce this?

`embrace-add` -- ESC -- selection surrounded by `^[`

All three package are installed and loaded, and I have ran `evil-embrace-enable-evil-surround-integration`.
