### ISSUE TITLE
Screencast too fast

### ISSUE THREAD

**Issue by tmalsburg** [cute-jumper/evil-embrace.el#3]
Thanks for this package, this is exactly what I wanted when installed evil-surround.  Looking forward to using this package.

It would be good, though, to slow down the screencast.

**Comment by cute-jumper** [comment]
Glad you find this helpful. Now that you mentioned it, I did find the screencast a little too fast. I probably don't have the original source for the gif now, so I'm guessing I would just write down the key sequences int the README.

**Comment by tmalsburg** [comment]
I'm sure there is a way to change the speed of a GIF, but writing the key sequences down would be helpful, too.

**Comment by cute-jumper** [comment]
You're right. A quick google helps me find the solution to slow down the GIF.

**Comment by tmalsburg** [comment]
Great, thank you!
