### ISSUE TITLE
Make operations repeatable with . operator

### ISSUE THREAD

**Issue by tmalsburg** [cute-jumper/evil-embrace.el#4]
For instance, `ysip"` adds quotes around a paragraph. It would be cool if I could repeat this on the next paragraph by just pressing `.`.

**Comment by cute-jumper** [comment]
Weird. It works in my Emacs. Can you give detailed steps to reproduce the problem?

**Comment by tmalsburg** [comment]
```
$ emacs --version
GNU Emacs 25.0.93.1
```

Then `emacs -q` and 

```
(require 'evil)
(evil-mode 1)
(require 'evil-surround)
(global-evil-surround-mode 1)
(setq evil-surround-keep-point t)
(add-hook 'org-mode-hook 'embrace-org-mode-hook)
(evil-embrace-enable-evil-surround-integration)
```

For testing I used this text:

```
te|st

test
```

`|` is the cursor.  I types `ysip"` and the paragraph the result was:

```
"
te|st
"

test
```
When I place the cursor on the second `test` and press `.` a number of different things can happen.  One result that I got was:

```
"
te|st
"
```

Another was

```
"
test
"

tetest

tetest
```

Another possible result is that nothing happens.

**Comment by tmalsburg** [comment]
Very annoying: when I debug my init file, I can't reproduce the problem but when I just start emacs normally it occurs reliably.  I'll keep trying ...

**Comment by tmalsburg** [comment]
Mystery solved: there was an old version of evil-surround somewhere in my load path.  Sorry for the noise.

**Comment by cute-jumper** [comment]
Good to know it is solved. Yeah, I remember evil-surround didn't support `.` operator some time ago.
